git mv content/job-families/alliances/alliance-business-development/index.html.md content/job-families/alliances/alliance-business-development/index.md
git mv content/job-families/alliances/alliances-job-family-matrix/index.html.md content/job-families/alliances/alliances-job-family-matrix/index.md
git mv content/job-families/alliances/alliances-manager/index.html.md content/job-families/alliances/alliances-manager/index.md
git mv content/job-families/board-of-directors/board_member/index.html.md content/job-families/board-of-directors/board_member/index.md
git mv content/job-families/chief-executive-officer/chief-of-staff/index.html.md content/job-families/chief-executive-officer/chief-of-staff/index.md
git mv content/job-families/chief-executive-officer/internal-strategy-intern/index.html.md content/job-families/chief-executive-officer/internal-strategy-intern/index.md
git mv content/job-families/chief-executive-officer/strategy-and-operations/index.html.md content/job-families/chief-executive-officer/strategy-and-operations/index.md
git mv content/job-families/engineering/acting-cos-to-the-cto/index.html.md content/job-families/engineering/acting-cos-to-the-cto/index.md
git mv content/job-families/engineering/backend-engineer/index.html.md content/job-families/engineering/backend-engineer/index.md
git mv content/job-families/engineering/cloud-native-engineer/index.html.md content/job-families/engineering/cloud-native-engineer/index.md
git mv content/job-families/engineering/database-engineer/index.html.md content/job-families/engineering/database-engineer/index.md
git mv content/job-families/engineering/development/backend/intermediate/index.html.md content/job-families/engineering/development/backend/intermediate/index.md
git mv content/job-families/engineering/development/backend/manager/index.html.md content/job-families/engineering/development/backend/manager/index.md
git mv content/job-families/engineering/development/backend/senior/index.html.md content/job-families/engineering/development/backend/senior/index.md
git mv content/job-families/engineering/development/backend/staff/index.html.md content/job-families/engineering/development/backend/staff/index.md
git mv content/job-families/engineering/development/frontend/associate/index.html.md content/job-families/engineering/development/frontend/associate/index.md
git mv content/job-families/engineering/development/frontend/intermediate/index.html.md content/job-families/engineering/development/frontend/intermediate/index.md
git mv content/job-families/engineering/development/frontend/manager/index.html.md content/job-families/engineering/development/frontend/manager/index.md
git mv content/job-families/engineering/development/frontend/senior/index.html.md content/job-families/engineering/development/frontend/senior/index.md
git mv content/job-families/engineering/development/frontend/staff/index.html.md content/job-families/engineering/development/frontend/staff/index.md
git mv content/job-families/engineering/development/fullstack/intermediate-fullstack-engineer.html.md content/job-families/engineering/development/fullstack/intermediate-fullstack-engineer.md
git mv content/job-families/engineering/development/management/director/index.html.md content/job-families/engineering/development/management/director/index.md
git mv content/job-families/engineering/development/management/distinguished/index.html.md content/job-families/engineering/development/management/distinguished/index.md
git mv content/job-families/engineering/development/management/fellow/index.html.md content/job-families/engineering/development/management/fellow/index.md
git mv content/job-families/engineering/development/management/fullstack-manager/index.html.md content/job-families/engineering/development/management/fullstack-manager/index.md
git mv content/job-families/engineering/development/management/principal-engineer/index.html.md content/job-families/engineering/development/management/principal-engineer/index.md
git mv content/job-families/engineering/development/management/senior-director/index.html.md content/job-families/engineering/development/management/senior-director/index.md
git mv content/job-families/engineering/development/management/senior-distinguished/index.html.md content/job-families/engineering/development/management/senior-distinguished/index.md
git mv content/job-families/engineering/development/management/senior-manager/index.html.md content/job-families/engineering/development/management/senior-manager/index.md
git mv content/job-families/engineering/development/management/vp/index.html.md content/job-families/engineering/development/management/vp/index.md
git mv content/job-families/engineering/distinguished-engineer-secure/index.html.md content/job-families/engineering/distinguished-engineer-secure/index.md
git mv content/job-families/engineering/engineering-management-quality/index.html.md content/job-families/engineering/engineering-management-quality/index.md
git mv content/job-families/engineering/engineering-management/index.html.md content/job-families/engineering/engineering-management/index.md
git mv content/job-families/engineering/fellow/index.html.md content/job-families/engineering/fellow/index.md
git mv content/job-families/engineering/general-manager-meltano/index.html.md content/job-families/engineering/general-manager-meltano/index.md
git mv content/job-families/engineering/incubation/engineer/index.html.md content/job-families/engineering/incubation/engineer/index.md
git mv content/job-families/engineering/incubation/management/vp/index.html.md content/job-families/engineering/incubation/management/vp/index.md
git mv content/job-families/engineering/infrastructure/backend-engineer/index.html.md content/job-families/engineering/infrastructure/backend-engineer/index.md
git mv content/job-families/engineering/infrastructure/database-reliability-engineer/index.html.md content/job-families/engineering/infrastructure/database-reliability-engineer/index.md
git mv content/job-families/engineering/infrastructure/distinguished-engineer/index.html.md content/job-families/engineering/infrastructure/distinguished-engineer/index.md
git mv content/job-families/engineering/infrastructure/engineering-fellow/index.html.md content/job-families/engineering/infrastructure/engineering-fellow/index.md
git mv content/job-families/engineering/infrastructure/engineering-management/index.html.md content/job-families/engineering/infrastructure/engineering-management/index.md
git mv content/job-families/engineering/infrastructure/site-reliability-engineer/index.html.md content/job-families/engineering/infrastructure/site-reliability-engineer/index.md
git mv content/job-families/engineering/monitoring-engineer/index.html.md content/job-families/engineering/monitoring-engineer/index.md
git mv content/job-families/engineering/monitoring-manager/index.html.md content/job-families/engineering/monitoring-manager/index.md
git mv content/job-families/engineering/quality/engineering-analytics/engineering-analyst/index.html.md content/job-families/engineering/quality/engineering-analytics/engineering-analyst/index.md
git mv content/job-families/engineering/quality/engineering-analytics/management/index.html.md content/job-families/engineering/quality/engineering-analytics/management/index.md
git mv content/job-families/engineering/software-engineer-in-test/index.html.md content/job-families/engineering/software-engineer-in-test/index.md
git mv content/job-families/engineering/software-engineer-intern/index.html.md content/job-families/engineering/software-engineer-intern/index.md
git mv content/job-families/engineering/support-engineer/index.html.md content/job-families/engineering/support-engineer/index.md
git mv content/job-families/engineering/support-management/index.html.md content/job-families/engineering/support-management/index.md
git mv content/job-families/engineering/support-operations-management/index.html.md content/job-families/engineering/support-operations-management/index.md
git mv content/job-families/engineering/support-readiness-specialist/index.html.md content/job-families/engineering/support-readiness-specialist/index.md
git mv content/job-families/engineering/vulnerability-research-engineer/index.html.md content/job-families/engineering/vulnerability-research-engineer/index.md
git mv content/job-families/engineering/vulnerability-research-manager/index.html.md content/job-families/engineering/vulnerability-research-manager/index.md
git mv content/job-families/expert/merge-request-coach/index.html.md content/job-families/expert/merge-request-coach/index.md
git mv content/job-families/expert/reliability/index.html.md content/job-families/expert/reliability/index.md
git mv content/job-families/finance/VP-Information-Technology/index.html.md content/job-families/finance/VP-Information-Technology/index.md
git mv content/job-families/finance/accountant/index.html.md content/job-families/finance/accountant/index.md
git mv content/job-families/finance/accounting-and-external-reporting-manager/index.html.md content/job-families/finance/accounting-and-external-reporting-manager/index.md
git mv content/job-families/finance/accounting-operations-manager/index.html.md content/job-families/finance/accounting-operations-manager/index.md
git mv content/job-families/finance/accounts-payable/index.html.md content/job-families/finance/accounts-payable/index.md
git mv content/job-families/finance/accounts-receivable/index.html.md content/job-families/finance/accounts-receivable/index.md
git mv content/job-families/finance/analytics-and-insights/index.html.md content/job-families/finance/analytics-and-insights/index.md
git mv content/job-families/finance/analytics-engineer/index.html.md content/job-families/finance/analytics-engineer/index.md
git mv content/job-families/finance/billing-gpo/index.html.md content/job-families/finance/billing-gpo/index.md
git mv content/job-families/finance/billing/index.html.md content/job-families/finance/billing/index.md
git mv content/job-families/finance/business-system-analyst/index.html.md content/job-families/finance/business-system-analyst/index.md
git mv content/job-families/finance/chief-financial-officer/index.html.md content/job-families/finance/chief-financial-officer/index.md
git mv content/job-families/finance/chief-of-staff-to-the-cfo/index.html.md content/job-families/finance/chief-of-staff-to-the-cfo/index.md
git mv content/job-families/finance/corporate-controller/accounting-operations/index.html.md content/job-families/finance/corporate-controller/accounting-operations/index.md
git mv content/job-families/finance/corporate-controller/international-accounting/index.html.md content/job-families/finance/corporate-controller/international-accounting/index.md
git mv content/job-families/finance/corporate-controller/sec-and-external-reporting/index.html.md content/job-families/finance/corporate-controller/sec-and-external-reporting/index.md
git mv content/job-families/finance/corporate-controller/treasury-manager/index.html.md content/job-families/finance/corporate-controller/treasury-manager/index.md
git mv content/job-families/finance/data-analyst/index.html.md content/job-families/finance/data-analyst/index.md
git mv content/job-families/finance/data-engineer/index.html.md content/job-families/finance/data-engineer/index.md
git mv content/job-families/finance/data-science/index.html.md content/job-families/finance/data-science/index.md
git mv content/job-families/finance/dir-data-and-analytics/index.html.md content/job-families/finance/dir-data-and-analytics/index.md
git mv content/job-families/finance/director-it-operations/index.html.md content/job-families/finance/director-it-operations/index.md
git mv content/job-families/finance/expense-specialist/index.html.md content/job-families/finance/expense-specialist/index.md
git mv content/job-families/finance/finance-planning-and-analysis/index.html.md content/job-families/finance/finance-planning-and-analysis/index.md
git mv content/job-families/finance/finance-systems-administrator/index.html.md content/job-families/finance/finance-systems-administrator/index.md
git mv content/job-families/finance/general-ledger-accounting/index.html.md content/job-families/finance/general-ledger-accounting/index.md
git mv content/job-families/finance/integrations-engineer/index.html.md content/job-families/finance/integrations-engineer/index.md
git mv content/job-families/finance/internal-audit/index.html.md content/job-families/finance/internal-audit/index.md
git mv content/job-families/finance/investor-relations/index.html.md content/job-families/finance/investor-relations/index.md
git mv content/job-families/finance/it-compliance/index.html.md content/job-families/finance/it-compliance/index.md
git mv content/job-families/finance/it-helpdesk-analyst/index.html.md content/job-families/finance/it-helpdesk-analyst/index.md
git mv content/job-families/finance/it-operations-system-engineer/index.html.md content/job-families/finance/it-operations-system-engineer/index.md
git mv content/job-families/finance/it-security-analyst/index.html.md content/job-families/finance/it-security-analyst/index.md
git mv content/job-families/finance/it-security-engineer/index.html.md content/job-families/finance/it-security-engineer/index.md
git mv content/job-families/finance/it-site-reliability-engineer/index.html.md content/job-families/finance/it-site-reliability-engineer/index.md
git mv content/job-families/finance/it-systems-engineer/index.html.md content/job-families/finance/it-systems-engineer/index.md
git mv content/job-families/finance/manager-data/index.html.md content/job-families/finance/manager-data/index.md
git mv content/job-families/finance/manager-it-security-operations/index.html.md content/job-families/finance/manager-it-security-operations/index.md
git mv content/job-families/finance/manager-it/index.html.md content/job-families/finance/manager-it/index.md
git mv content/job-families/finance/pao-jf/index.html.md content/job-families/finance/pao-jf/index.md
git mv content/job-families/finance/payroll/index.html.md content/job-families/finance/payroll/index.md
git mv content/job-families/finance/procurement-operations/index.html.md content/job-families/finance/procurement-operations/index.md
git mv content/job-families/finance/program-management-BT/index.html.md content/job-families/finance/program-management-BT/index.md
git mv content/job-families/finance/revenue-accounting/index.html.md content/job-families/finance/revenue-accounting/index.md
git mv content/job-families/finance/revenue-gpo/index.html.md content/job-families/finance/revenue-gpo/index.md
git mv content/job-families/finance/senior-director-enterprise-applications/index.html.md content/job-families/finance/senior-director-enterprise-applications/index.md
git mv content/job-families/finance/sox-compliance-analyst/index.html.md content/job-families/finance/sox-compliance-analyst/index.md
git mv content/job-families/finance/statutory-accounting-and-reporting/index.html.md content/job-families/finance/statutory-accounting-and-reporting/index.md
git mv content/job-families/finance/stock-administrator/index.html.md content/job-families/finance/stock-administrator/index.md
git mv content/job-families/finance/tax/index.html.md content/job-families/finance/tax/index.md
git mv content/job-families/finance/technical-accounting/index.html.md content/job-families/finance/technical-accounting/index.md
git mv content/job-families/finance/vice-president-cash-management/index.html.md content/job-families/finance/vice-president-cash-management/index.md
git mv content/job-families/finance/vice-president-of-tax/index.html.md content/job-families/finance/vice-president-of-tax/index.md
git mv content/job-families/finance/vp-finance/index.html.md content/job-families/finance/vp-finance/index.md
git mv content/job-families/legal-and-corporate-affairs/Director-of-Compliance/index.html.md content/job-families/legal-and-corporate-affairs/Director-of-Compliance/index.md
git mv content/job-families/legal-and-corporate-affairs/chief-legal-officer/index.html.md content/job-families/legal-and-corporate-affairs/chief-legal-officer/index.md
git mv content/job-families/legal-and-corporate-affairs/contract-manager/index.html.md content/job-families/legal-and-corporate-affairs/contract-manager/index.md
git mv content/job-families/legal-and-corporate-affairs/corporate-development/index.html.md content/job-families/legal-and-corporate-affairs/corporate-development/index.md
git mv content/job-families/legal-and-corporate-affairs/director-legal-us/index.html.md content/job-families/legal-and-corporate-affairs/director-legal-us/index.md
git mv content/job-families/legal-and-corporate-affairs/environmental-social-governance/index.html.md content/job-families/legal-and-corporate-affairs/environmental-social-governance/index.md
git mv content/job-families/legal-and-corporate-affairs/legal-counsel/index.html.md content/job-families/legal-and-corporate-affairs/legal-counsel/index.md
git mv content/job-families/legal-and-corporate-affairs/legal-intern/index.html.md content/job-families/legal-and-corporate-affairs/legal-intern/index.md
git mv content/job-families/legal-and-corporate-affairs/legal-operations/index.html.md content/job-families/legal-and-corporate-affairs/legal-operations/index.md
git mv content/job-families/legal-and-corporate-affairs/paralegal/index.html.md content/job-families/legal-and-corporate-affairs/paralegal/index.md
git mv content/job-families/marketing/VP-Developer-Relations/index.html.md content/job-families/marketing/VP-Developer-Relations/index.md
git mv content/job-families/marketing/account-based-marketing-manager/index.html.md content/job-families/marketing/account-based-marketing-manager/index.md
git mv content/job-families/marketing/account-research-specialist/index.html.md content/job-families/marketing/account-research-specialist/index.md
git mv content/job-families/marketing/all-remote-marketing/index.html.md content/job-families/marketing/all-remote-marketing/index.md
git mv content/job-families/marketing/analysts-relations-manager/index.html.md content/job-families/marketing/analysts-relations-manager/index.md
git mv content/job-families/marketing/awareness-campaign-manager/index.html.md content/job-families/marketing/awareness-campaign-manager/index.md
git mv content/job-families/marketing/brand-designer/index.html.md content/job-families/marketing/brand-designer/index.md
git mv content/job-families/marketing/brand-growth/index.html.md content/job-families/marketing/brand-growth/index.md
git mv content/job-families/marketing/brand-leadership/index.html.md content/job-families/marketing/brand-leadership/index.md
git mv content/job-families/marketing/channel-and-alliances-marketing/index.html.md content/job-families/marketing/channel-and-alliances-marketing/index.md
git mv content/job-families/marketing/chief-marketing-officer/index.html.md content/job-families/marketing/chief-marketing-officer/index.md
git mv content/job-families/marketing/code-contributor-program-manager/index.html.md content/job-families/marketing/code-contributor-program-manager/index.md
git mv content/job-families/marketing/community-advocate/index.html.md content/job-families/marketing/community-advocate/index.md
git mv content/job-families/marketing/community-programs/index.html.md content/job-families/marketing/community-programs/index.md
git mv content/job-families/marketing/content-designer/index.html.md content/job-families/marketing/content-designer/index.md
git mv content/job-families/marketing/content-marketing/index.html.md content/job-families/marketing/content-marketing/index.md
git mv content/job-families/marketing/corporate-communications-manager/index.html.md content/job-families/marketing/corporate-communications-manager/index.md
git mv content/job-families/marketing/corporate-events/index.html.md content/job-families/marketing/corporate-events/index.md
git mv content/job-families/marketing/creative-operations/index.html.md content/job-families/marketing/creative-operations/index.md
git mv content/job-families/marketing/customer-lifecycle-marketing-manager/index.html.md content/job-families/marketing/customer-lifecycle-marketing-manager/index.md
git mv content/job-families/marketing/demand-generation-manager/index.html.md content/job-families/marketing/demand-generation-manager/index.md
git mv content/job-families/marketing/demand-generation-specialist/index.html.md content/job-families/marketing/demand-generation-specialist/index.md
git mv content/job-families/marketing/designer/index.html.md content/job-families/marketing/designer/index.md
git mv content/job-families/marketing/developer-evangelist/index.html.md content/job-families/marketing/developer-evangelist/index.md
git mv content/job-families/marketing/developer-marketing-manager/index.html.md content/job-families/marketing/developer-marketing-manager/index.md
git mv content/job-families/marketing/digital-experience/index.html.md content/job-families/marketing/digital-experience/index.md
git mv content/job-families/marketing/digital-marketing-programs-manager/index.html.md content/job-families/marketing/digital-marketing-programs-manager/index.md
git mv content/job-families/marketing/digital-production-manager/index.html.md content/job-families/marketing/digital-production-manager/index.md
git mv content/job-families/marketing/director-corporate-marketing/index.html.md content/job-families/marketing/director-corporate-marketing/index.md
git mv content/job-families/marketing/director-field-marketing/index.html.md content/job-families/marketing/director-field-marketing/index.md
git mv content/job-families/marketing/director-marketing-operations/index.html.md content/job-families/marketing/director-marketing-operations/index.md
git mv content/job-families/marketing/director-of-community-relations/index.html.md content/job-families/marketing/director-of-community-relations/index.md
git mv content/job-families/marketing/director-technical-evangelism/index.html.md content/job-families/marketing/director-technical-evangelism/index.md
git mv content/job-families/marketing/editor/index.html.md content/job-families/marketing/editor/index.md
git mv content/job-families/marketing/evangelist-program-manager/index.html.md content/job-families/marketing/evangelist-program-manager/index.md
git mv content/job-families/marketing/field-marketing-manager-public-sector/index.html.md content/job-families/marketing/field-marketing-manager-public-sector/index.md
git mv content/job-families/marketing/field-marketing-manager/index.html.md content/job-families/marketing/field-marketing-manager/index.md
git mv content/job-families/marketing/field-marketing-specialist/index.html.md content/job-families/marketing/field-marketing-specialist/index.md
git mv content/job-families/marketing/frontend-engineer-marketing/index.html.md content/job-families/marketing/frontend-engineer-marketing/index.md
git mv content/job-families/marketing/fullstack-engineer-marketing/index.html.md content/job-families/marketing/fullstack-engineer-marketing/index.md
git mv content/job-families/marketing/gitlab-for-education/index.html.md content/job-families/marketing/gitlab-for-education/index.md
git mv content/job-families/marketing/global-content-manager/index.html.md content/job-families/marketing/global-content-manager/index.md
git mv content/job-families/marketing/global-programs-manager/index.html.md content/job-families/marketing/global-programs-manager/index.md
git mv content/job-families/marketing/globalization/index.html.md content/job-families/marketing/globalization/index.md
git mv content/job-families/marketing/growth-product-manager/index.html.md content/job-families/marketing/growth-product-manager/index.md
git mv content/job-families/marketing/illustrator/index.html.md content/job-families/marketing/illustrator/index.md
git mv content/job-families/marketing/inbound-marketing/index.html.md content/job-families/marketing/inbound-marketing/index.md
git mv content/job-families/marketing/integrated-marketing/index.html.md content/job-families/marketing/integrated-marketing/index.md
git mv content/job-families/marketing/manager-marketing-programs/index.html.md content/job-families/marketing/manager-marketing-programs/index.md
git mv content/job-families/marketing/marketing-campaign-manager/index.html.md content/job-families/marketing/marketing-campaign-manager/index.md
git mv content/job-families/marketing/marketing-intern/index.html.md content/job-families/marketing/marketing-intern/index.md
git mv content/job-families/marketing/marketing-operations-associate/index.html.md content/job-families/marketing/marketing-operations-associate/index.md
git mv content/job-families/marketing/marketing-operations-manager/index.html.md content/job-families/marketing/marketing-operations-manager/index.md
git mv content/job-families/marketing/marketing-program-manager/index.html.md content/job-families/marketing/marketing-program-manager/index.md
git mv content/job-families/marketing/marketing-strategy-and-operations/index.html.md content/job-families/marketing/marketing-strategy-and-operations/index.md
git mv content/job-families/marketing/marketing-strategy/index.html.md content/job-families/marketing/marketing-strategy/index.md
git mv content/job-families/marketing/open-source-program-manager/index.html.md content/job-families/marketing/open-source-program-manager/index.md
git mv content/job-families/marketing/pr-manager/index.html.md content/job-families/marketing/pr-manager/index.md
git mv content/job-families/marketing/product-designer-ux-marketing/index.html.md content/job-families/marketing/product-designer-ux-marketing/index.md
git mv content/job-families/marketing/product-manager-marketing/index.html.md content/job-families/marketing/product-manager-marketing/index.md
git mv content/job-families/marketing/product-marketing-management/index.html.md content/job-families/marketing/product-marketing-management/index.md
git mv content/job-families/marketing/product-marketing-manager-public-sector/index.html.md content/job-families/marketing/product-marketing-manager-public-sector/index.md
git mv content/job-families/marketing/product-marketing-manager/index.html.md content/job-families/marketing/product-marketing-manager/index.md
git mv content/job-families/marketing/production-designer/index.html.md content/job-families/marketing/production-designer/index.md
git mv content/job-families/marketing/reference-program-manager/index.html.md content/job-families/marketing/reference-program-manager/index.md
git mv content/job-families/marketing/sales-development-enablement-programs/index.html.md content/job-families/marketing/sales-development-enablement-programs/index.md
git mv content/job-families/marketing/sales-development-leadership/index.html.md content/job-families/marketing/sales-development-leadership/index.md
git mv content/job-families/marketing/sales-development-manager-commercial/index.html.md content/job-families/marketing/sales-development-manager-commercial/index.md
git mv content/job-families/marketing/sales-development-manager/index.html.md content/job-families/marketing/sales-development-manager/index.md
git mv content/job-families/marketing/sales-development-marketing-operations/index.html.md content/job-families/marketing/sales-development-marketing-operations/index.md
git mv content/job-families/marketing/sales-development-representative/index.html.md content/job-families/marketing/sales-development-representative/index.md
git mv content/job-families/marketing/sales-development-solutions-architect/index.html.md content/job-families/marketing/sales-development-solutions-architect/index.md
git mv content/job-families/marketing/senior-director-of-growth-marketing/index.html.md content/job-families/marketing/senior-director-of-growth-marketing/index.md
git mv content/job-families/marketing/senior-sales-development-manager-acceleration/index.html.md content/job-families/marketing/senior-sales-development-manager-acceleration/index.md
git mv content/job-families/marketing/social-marketing-manager/index.html.md content/job-families/marketing/social-marketing-manager/index.md
git mv content/job-families/marketing/technical-marketing-manager/index.html.md content/job-families/marketing/technical-marketing-manager/index.md
git mv content/job-families/marketing/vice-president-of-product-marketing/index.html.md content/job-families/marketing/vice-president-of-product-marketing/index.md
git mv content/job-families/marketing/vp-of-business-development-and-strategy/index.html.md content/job-families/marketing/vp-of-business-development-and-strategy/index.md
git mv content/job-families/marketing/vp-of-revenue-marketing/index.html.md content/job-families/marketing/vp-of-revenue-marketing/index.md
git mv content/job-families/people-group/absence-management/index.html.md content/job-families/people-group/absence-management/index.md
git mv content/job-families/people-group/candidate-experience/index.html.md content/job-families/people-group/candidate-experience/index.md
git mv content/job-families/people-group/chief-people-officer/index.html.md content/job-families/people-group/chief-people-officer/index.md
git mv content/job-families/people-group/diversity-inclusion-partner/index.html.md content/job-families/people-group/diversity-inclusion-partner/index.md
git mv content/job-families/people-group/employment-solutions/index.html.md content/job-families/people-group/employment-solutions/index.md
git mv content/job-families/people-group/executive-business-administrator/index.html.md content/job-families/people-group/executive-business-administrator/index.md
git mv content/job-families/people-group/executive-recruiter/index.html.md content/job-families/people-group/executive-recruiter/index.md
git mv content/job-families/people-group/instructional-designer/index.html.md content/job-families/people-group/instructional-designer/index.md
git mv content/job-families/people-group/leadership-people-operations-tech-analytics/index.html.md content/job-families/people-group/leadership-people-operations-tech-analytics/index.md
git mv content/job-families/people-group/learning-development/index.html.md content/job-families/people-group/learning-development/index.md
git mv content/job-families/people-group/learning-system-administrator/index.html.md content/job-families/people-group/learning-system-administrator/index.md
git mv content/job-families/people-group/people-business-partner/index.html.md content/job-families/people-group/people-business-partner/index.md
git mv content/job-families/people-group/people-communications-engagement/index.html.md content/job-families/people-group/people-communications-engagement/index.md
git mv content/job-families/people-group/people-compliance/index.html.md content/job-families/people-group/people-compliance/index.md
git mv content/job-families/people-group/people-connect/index.html.md content/job-families/people-group/people-connect/index.md
git mv content/job-families/people-group/people-leadership/index.html.md content/job-families/people-group/people-leadership/index.md
git mv content/job-families/people-group/people-ops-fullstack-engineer/index.html.md content/job-families/people-group/people-ops-fullstack-engineer/index.md
git mv content/job-families/people-group/people-systems-and-analytics/index.html.md content/job-families/people-group/people-systems-and-analytics/index.md
git mv content/job-families/people-group/recruiter/index.html.md content/job-families/people-group/recruiter/index.md
git mv content/job-families/people-group/recruiting-operations-insights/index.html.md content/job-families/people-group/recruiting-operations-insights/index.md
git mv content/job-families/people-group/recruiting-sourcer/index.html.md content/job-families/people-group/recruiting-sourcer/index.md
git mv content/job-families/people-group/talent-acquisition-leadership/index.html.md content/job-families/people-group/talent-acquisition-leadership/index.md
git mv content/job-families/people-group/talent-brand-and-talent-acquisition-enablement/index.html.md content/job-families/people-group/talent-brand-and-talent-acquisition-enablement/index.md
git mv content/job-families/people-group/team-member-relations/index.html.md content/job-families/people-group/team-member-relations/index.md
git mv content/job-families/people-group/total-rewards/index.html.md content/job-families/people-group/total-rewards/index.md
git mv content/job-families/product/chief-product-officer/index.html.md content/job-families/product/chief-product-officer/index.md
git mv content/job-families/product/corporate-development-engineer/index.html.md content/job-families/product/corporate-development-engineer/index.md
git mv content/job-families/product/pricing/index.html.md content/job-families/product/pricing/index.md
git mv content/job-families/product/product-analyst/index.html.md content/job-families/product/product-analyst/index.md
git mv content/job-families/product/product-design-management/index.html.md content/job-families/product/product-design-management/index.md
git mv content/job-families/product/product-management-leadership/index.html.md content/job-families/product/product-management-leadership/index.md
git mv content/job-families/product/product-operations/index.html.md content/job-families/product/product-operations/index.md
git mv content/job-families/product/technical-writer/index.html.md content/job-families/product/technical-writer/index.md
git mv content/job-families/product/technical-writing-manager/index.html.md content/job-families/product/technical-writing-manager/index.md
git mv content/job-families/product/ux-fullstack-engineer/index.html.md content/job-families/product/ux-fullstack-engineer/index.md
git mv content/job-families/product/ux-research-manager/index.html.md content/job-families/product/ux-research-manager/index.md
git mv content/job-families/product/ux-research-operations-coordinator/index.html.md content/job-families/product/ux-research-operations-coordinator/index.md
git mv content/job-families/product/ux-researcher/index.html.md content/job-families/product/ux-researcher/index.md
git mv content/job-families/product/vp-product/index.html.md content/job-families/product/vp-product/index.md
git mv content/job-families/sales/area-vice-president-of-sales/index.html.md content/job-families/sales/area-vice-president-of-sales/index.md
git mv content/job-families/sales/business-systems-architect/index.html.md content/job-families/sales/business-systems-architect/index.md
git mv content/job-families/sales/business-value-manager/index.html.md content/job-families/sales/business-value-manager/index.md
git mv content/job-families/sales/capture/index.html.md content/job-families/sales/capture/index.md
git mv content/job-families/sales/channel-program-manager/index.html.md content/job-families/sales/channel-program-manager/index.md
git mv content/job-families/sales/channel-projects-go-to-market/index.html.md content/job-families/sales/channel-projects-go-to-market/index.md
git mv content/job-families/sales/channel-services/index.html.md content/job-families/sales/channel-services/index.md
git mv content/job-families/sales/chief-of-staff-cro/index.html.md content/job-families/sales/chief-of-staff-cro/index.md
git mv content/job-families/sales/country-manager-for-italy/index.html.md content/job-families/sales/country-manager-for-italy/index.md
git mv content/job-families/sales/customer-success-management/index.html.md content/job-families/sales/customer-success-management/index.md
git mv content/job-families/sales/customer-success-operations-internship/index.html.md content/job-families/sales/customer-success-operations-internship/index.md
git mv content/job-families/sales/customer-success-operations/index.html.md content/job-families/sales/customer-success-operations/index.md
git mv content/job-families/sales/director-channel-programs-and-enablement/index.html.md content/job-families/sales/director-channel-programs-and-enablement/index.md
git mv content/job-families/sales/director-customer-operations/index.html.md content/job-families/sales/director-customer-operations/index.md
git mv content/job-families/sales/director-customer-programs/index.html.md content/job-families/sales/director-customer-programs/index.md
git mv content/job-families/sales/director-online-sales-and-self-service-growth/index.html.md content/job-families/sales/director-online-sales-and-self-service-growth/index.md
git mv content/job-families/sales/federal-advisory-board-member/index.html.md content/job-families/sales/federal-advisory-board-member/index.md
git mv content/job-families/sales/field-communications/index.html.md content/job-families/sales/field-communications/index.md
git mv content/job-families/sales/gtm-planning-and-operations/index.html.md content/job-families/sales/gtm-planning-and-operations/index.md
git mv content/job-families/sales/inside-sales-mid-market/index.html.md content/job-families/sales/inside-sales-mid-market/index.md
git mv content/job-families/sales/inside-sales/index.html.md content/job-families/sales/inside-sales/index.md
git mv content/job-families/sales/job-professional-services-engagement-manager/index.html.md content/job-families/sales/job-professional-services-engagement-manager/index.md
git mv content/job-families/sales/online-sales-operations/index.html.md content/job-families/sales/online-sales-operations/index.md
git mv content/job-families/sales/partner-help-desk-specialist/index.html.md content/job-families/sales/partner-help-desk-specialist/index.md
git mv content/job-families/sales/partner-integration-engineering/index.html.md content/job-families/sales/partner-integration-engineering/index.md
git mv content/job-families/sales/professional-services-architect/index.html.md content/job-families/sales/professional-services-architect/index.md
git mv content/job-families/sales/professional-services-education-services/index.html.md content/job-families/sales/professional-services-education-services/index.md
git mv content/job-families/sales/professional-services-operations/index.html.md content/job-families/sales/professional-services-operations/index.md
git mv content/job-families/sales/professional-services-practice-engineer/index.html.md content/job-families/sales/professional-services-practice-engineer/index.md
git mv content/job-families/sales/professional-services-practice-manager/index.html.md content/job-families/sales/professional-services-practice-manager/index.md
git mv content/job-families/sales/professional-services-project-manager/index.html.md content/job-families/sales/professional-services-project-manager/index.md
git mv content/job-families/sales/professional-services-solutions-manager/index.html.md content/job-families/sales/professional-services-solutions-manager/index.md
git mv content/job-families/sales/program-manager-customer-programs/index.html.md content/job-families/sales/program-manager-customer-programs/index.md
git mv content/job-families/sales/public-sector-inside-sales/index.html.md content/job-families/sales/public-sector-inside-sales/index.md
git mv content/job-families/sales/pubsec-entity-board-director/index.html.md content/job-families/sales/pubsec-entity-board-director/index.md
git mv content/job-families/sales/renewal-manager/index.html.md content/job-families/sales/renewal-manager/index.md
git mv content/job-families/sales/renewal-operations-analyst/index.html.md content/job-families/sales/renewal-operations-analyst/index.md
git mv content/job-families/sales/renewals/index.html.md content/job-families/sales/renewals/index.md
git mv content/job-families/sales/revenue-programs/index.html.md content/job-families/sales/revenue-programs/index.md
git mv content/job-families/sales/sales-commissions/index.html.md content/job-families/sales/sales-commissions/index.md
git mv content/job-families/sales/sales-operations/senior-manager-of-data-intelligence/index.html.md content/job-families/sales/sales-operations/senior-manager-of-data-intelligence/index.md
git mv content/job-families/sales/sales-strategy/index.html.md content/job-families/sales/sales-strategy/index.md
git mv content/job-families/sales/self-service-online-sales-growth/index.html.md content/job-families/sales/self-service-online-sales-growth/index.md
git mv content/job-families/sales/senior-manager-online-sales-self-service-product-data-analytics/index.html.md content/job-families/sales/senior-manager-online-sales-self-service-product-data-analytics/index.md
git mv content/job-families/sales/senior-manager-self-service-customer-engagement/index.html.md content/job-families/sales/senior-manager-self-service-customer-engagement/index.md
git mv content/job-families/sales/solutions-architect/index.html.md content/job-families/sales/solutions-architect/index.md
git mv content/job-families/sales/technical-enablement-program-manager/index.html.md content/job-families/sales/technical-enablement-program-manager/index.md
git mv content/job-families/sales/technical-instructional-designer/index.html.md content/job-families/sales/technical-instructional-designer/index.md
git mv content/job-families/sales/technical-writer-customer-programs/index.html.md content/job-families/sales/technical-writer-customer-programs/index.md
git mv content/job-families/sales/vice-president-global-enterprise-sales/index.html.md content/job-families/sales/vice-president-global-enterprise-sales/index.md
git mv content/job-families/sales/vice-president-online-sales-and-self-service/index.html.md content/job-families/sales/vice-president-online-sales-and-self-service/index.md
git mv content/job-families/sales/vp-of-field-operations/index.html.md content/job-families/sales/vp-of-field-operations/index.md
git mv content/job-families/sales/vp-revenue-operations/index.html.md content/job-families/sales/vp-revenue-operations/index.md
git mv content/job-families/security/application-security/index.html.md content/job-families/security/application-security/index.md
git mv content/job-families/security/external-security-communications/index.html.md content/job-families/security/external-security-communications/index.md
git mv content/job-families/security/facility-security-officer/index.html.md content/job-families/security/facility-security-officer/index.md
git mv content/job-families/security/field-security/index.html.md content/job-families/security/field-security/index.md
git mv content/job-families/security/infrastructure-security/index.html.md content/job-families/security/infrastructure-security/index.md
git mv content/job-families/security/red-team/index.html.md content/job-families/security/red-team/index.md
git mv content/job-families/security/security-analyst/index.html.md content/job-families/security/security-analyst/index.md
git mv content/job-families/security/security-automation/index.html.md content/job-families/security/security-automation/index.md
git mv content/job-families/security/security-compliance/index.html.md content/job-families/security/security-compliance/index.md
git mv content/job-families/security/security-engineer/index.html.md content/job-families/security/security-engineer/index.md
git mv content/job-families/security/security-governance/index.html.md content/job-families/security/security-governance/index.md
git mv content/job-families/security/security-incident-response-team/index.html.md content/job-families/security/security-incident-response-team/index.md
git mv content/job-families/security/security-leadership/index.html.md content/job-families/security/security-leadership/index.md
git mv content/job-families/security/security-logging/index.html.md content/job-families/security/security-logging/index.md
git mv content/job-families/security/security-program-manager/index.html.md content/job-families/security/security-program-manager/index.md
git mv content/job-families/security/security-research/index.html.md content/job-families/security/security-research/index.md
git mv content/job-families/security/security-risk/index.html.md content/job-families/security/security-risk/index.md
git mv content/job-families/security/threat-intelligence-engineer/index.html.md content/job-families/security/threat-intelligence-engineer/index.md
git mv content/job-families/security/trust-and-safety/index.html.md content/job-families/security/trust-and-safety/index.md
git mv content/job-families/security/vulnerability-management/index.html.md content/job-families/security/vulnerability-management/index.md
git mv content/job-families/specialist/backstage/index.html.md content/job-families/specialist/backstage/index.md
git mv content/job-families/specialist/distributed-systems/index.html.md content/job-families/specialist/distributed-systems/index.md
git mv content/job-families/specialist/prometheus/index.html.md content/job-families/specialist/prometheus/index.md
